#!/bin/bash
# Fetch one image per article from Wikipedia/Commons.
# Each article slug maps to a Wikipedia article title; we pull that page's
# lead image, save it as public/images/<slug>.<ext>, and record attribution
# in public/images/credits.json.
#
# Idempotent: skips re-downloading images that already exist, but ALWAYS
# rebuilds credits.json from scratch so partial runs leave clean metadata.

set -uo pipefail

DEST="public/images"
UA="KiriPedia/1.0 (https://kiripedia.org; contact projectmamad48@gmail.com)"
mkdir -p "$DEST"
CREDITS="$DEST/credits.json"

# slug=wikipedia_title (URL-encoded as needed)
# Rule for biographies (People): the picture must be of that person, or the
# article gets none. A flag, a city skyline or an agency seal in an infobox
# reads as "this is the subject" — 46 biographies were carrying exactly that
# and were unmapped on 2026-08-05 rather than given a better stand-in.
MAPPING=(
  "frank-snepp=Frank_Snepp"
  "kyriakos-mitsotakis=Kyriakos_Mitsotakis"
  "the-strike-on-ahmadinejads-house=Mahmoud_Ahmadinejad"
  "erbil-and-the-kurdish-autonomy-question=Erbil"
  "iranian-suicide-drones=HESA_Shahed_136"
  "us-drc-relations=Democratic_Republic_of_the_Congo"
  "the-kenya-mission=Kenya"
  "the-bbc-and-the-sanctions-coverage=BBC"
  "the-al-mayadeen-debate=Al_Mayadeen"
  "al-jazeera-blocked-in-the-united-states=Al_Jazeera"
  "the-uss-gerald-ford-plumbing=USS_Gerald_R._Ford"
  "hot-bunking=Hot_racking"
  "the-vietnam-speech=Hanoi"
  "sports-and-the-steelers-bar=Pittsburgh_Steelers"
  "trumps-supreme-court-appointees=Supreme_Court_of_the_United_States"
  "the-east-mediterranean-gas-partnership=East_Mediterranean_Gas_Forum"
  "closing-the-gulf-embassies=Persian_Gulf"
  "the-ai-he-uses=Perplexity_AI"
  "the-white-house-tip=White_House"
  "a-policy-support-organization=Central_Intelligence_Agency"
  "naftali-bennett=Naftali_Bennett"
  "the-samson-option=Samson_Option"
  "the-ras-laffan-strike=Ras_Laffan"
  "south-pars-and-the-north-dome=Persian_Gulf"
  "the-f-35-shootdown=Lockheed_Martin_F-35_Lightning_II"
  "the-knesset-death-penalty-law=Knesset"
  "the-danish-greenland-demolition-plan=Greenland"
  "the-cyprus-naval-buildup-2026=Cyprus"
  "the-hajj-ban-as-leverage=Hajj"
  "iranian-underground-missile-silos=Missile_launch_facility"
  "strikes-on-us-bases-2026=Incirlik_Air_Base"
  "south-lebanon-displacement-2026=Southern_Lebanon"
  "the-two-hundred-billion-war-request=The_Pentagon"
  "advice-to-an-aspiring-intelligence-analyst=Intelligence_analysis"
  "the-spy-who-talked-too-much=The_New_Yorker"
  "louise-mensch=Louise_Mensch"
  "laura-loomer=Laura_Loomer"
  "patrick-bet-david=Patrick_Bet-David"
  "gulf-intelligence-services=Gulf_Cooperation_Council"
  "the-buried-senate-documents=United_States_Senate"
  "charlie-kirk=Charlie_Kirk"
  "turning-point-usa=Turning_Point_USA"
  "max-blumenthal=Max_Blumenthal"
  "israeli-strike-on-qatar=2025_Israeli_strike_on_Doha"
  "mossad-networks-in-iran=Mossad"
  "mosaic-concept=Mossad"
  "unusually-violent-society=Gun_violence_in_the_United_States"
  "two-party-system=Two-party_system"
  "middle-east-forum=Middle_East_Forum"
  "al-julani=Ahmed_al-Sharaa"
  "barbara-leaf=Barbara_A._Leaf"
  "blackmail-in-recruitment=Blackmail"
  "origins-of-al-qaeda=Al-Qaeda"
  "cia-as-policy-support-agency=Central_Intelligence_Agency"
  "executive-assistant-to-the-deputy-director-for-operations=Directorate_of_Operations_(CIA)"
  "cheney-airstrip-question=Dick_Cheney"
  "scott-horton=Scott_Horton_(radio_host)"
  "greater-israel=Zionism"
  "2023-classified-documents-scandal=Biden_classified_documents_incident"
  "carrying-classified-out-of-a-scif=Sensitive_Compartmented_Information_Facility"
  "pillow-talk-disclosure-case=Central_Intelligence_Agency"
  "sensitive-but-unclassified=Controlled_Unclassified_Information"
  "classified-email=SIPRNet"
  "over-classification=Classified_information_in_the_United_States"
  "ukraine-call-whistleblower=Trump-Ukraine_scandal"
  "qasem-soleimani=Qasem_Soleimani"
  "jeremy-hammond=Jeremy_Hammond"
  "opcw-douma-investigation=Douma_chemical_attack"
  "upmc-whistleblower-case=University_of_Pittsburgh_Medical_Center"
  "corporate-whistleblower-protections=Whistleblower_protection_in_the_United_States"
  "operation-spiderweb=Operation_Spiderweb"
  "ukraine-settlement-prediction=Russian_invasion_of_Ukraine"
  "weaponization-subcommittee=Select_Subcommittee_on_the_Weaponization_of_the_Federal_Government"
  "cointelpro=COINTELPRO"
  "jim-bamford=James_Bamford"
  "fbi-raid-on-kiriakou-s-home=Federal_Bureau_of_Investigation"
  "taliban=Taliban"
  "peace-and-friendship-bridge=China-Pakistan_relations"
  "haiti=Haiti"
  "cuba-protests-2021=2021_Cuban_protests"
  "daniel-ortega=Daniel_Ortega"
  "caleb-maupin=Caleb_Maupin"
  "the-backstory=Radio_Sputnik"
  "syria-regime-change-template=Fall_of_the_Assad_regime"
  "hamid-karzai=Hamid_Karzai"
  "assassination-approval-process=Presidential_finding"
  "the-west-africa-cocaine-route=Illegal_drug_trade_in_Africa"
  "no-plan-for-day-two=Regime_change"
  "covert-action-program=Covert_operation"
  "maria-corina-machado=Maria_Corina_Machado"
  "the-libyan-constitution-unveiling=Constitution_of_Libya"
  "dewey-clarridge=Duane_Clarridge"
  "jack-devine=Jack_Devine"
  "music-as-torture=Music_in_psychological_operations"
  "justice-department-self-immolation-attempt=Self-immolation"
  "jim-moran=Jim_Moran"
  "charles-samuels=Charles_E._Samuels_Jr."
  "prison-legal-news=Prison_Legal_News"
  "this-desk-kills-fascism=Woody_Guthrie"
  "prison-medical-care=Federal_Correctional_Institution,_Loretto"
  "mass-incarceration-critique=Incarceration_in_the_United_States"
  "administrative-remedy-process=Federal_Bureau_of_Prisons"
  "public-safety-factor=Federal_Bureau_of_Prisons"
  "panetta-bin-laden-disclosure=Leon_Panetta"
  "seyyed-hossein-nasr=Seyyed_Hossein_Nasr"
  "domino-theory=Domino_theory"
  "international-criminal-court=International_Criminal_Court"
  "sharia-law=Sharia"
  "contra-rebels=Contras"
  "dark-alliance=Dark_Alliance"
  "international-spy-museum=International_Spy_Museum"
  "hague-invasion-act=American_Service-Members'_Protection_Act"
  "leadership-profiling=Psychological_profiling"
  "f-35-sale-to-turkey=Lockheed_Martin_F-35_Lightning_II"
  "oliver-stone=Oliver_Stone"
  "prince-andrew=Prince Andrew, Duke of York"
  "marjorie-taylor-greene=Marjorie_Taylor_Greene"
  "sergey-lavrov=Sergey_Lavrov"
  "tony-blinken=Antony_Blinken"
  "muslim-brotherhood-designation=Muslim_Brotherhood"
  "islamofascism-term=Islamofascism"
  "saudi-military-composition=Armed_Forces_of_Saudi_Arabia"
  "iran-iraq-war-intelligence-switching=Iran-Iraq_War"
  "harry-truman-israel-regret=Harry_S._Truman"
  "nixon-israeli-security-guarantee=Richard_Nixon"
  "netanyahu-nuclear-threat-to-trump=Benjamin_Netanyahu"
  "israel-non-extradition-of-jews=Extradition_law_in_Israel"
  "epstein-files-beef-jerky-anomaly=Jeffrey_Epstein"
  "thirty-year-mandatory-declassification=Declassification"
  "gulf-consultations-before-the-iran-war=Persian_Gulf"
  "kiriakou-public-speaking-training=Public_speaking"
  "liberty-university=Liberty University"
  "james-woolsey=James_Woolsey"
  "yasser-arafat=Yasser_Arafat"
  "houthis=Houthi_movement"
  "bab-al-mandab=Bab-el-Mandeb"
  "ali-abdullah-saleh=Ali_Abdullah_Saleh"
  "angry-birds=Angry_Birds"
  "mike-johnson=Mike_Johnson"
  "saudi-nuclear-program=Nuclear_program_of_Saudi_Arabia"
  "cyprus-green-line=Green_Line_(Cyprus)"
  "ndaa-section-219=National_Defense_Authorization_Act"
  "palestinians-in-the-gulf=Palestinian_diaspora"
  "israeli-espionage-in-the-united-states=Israel–United_States_relations"
  "afia-sadiki=Aafia_Siddiqui"
  "agnes-von-kurowsky-grave-story=Agnes_von_Kurowsky"
  "alan-dershowitz=Alan_Dershowitz"
  "avril-haines=Avril_Haines"
  "bill-burns=William_J._Burns_(diplomat)"
  "dianne-feinstein=Dianne_Feinstein"
  "greenland=Greenland"
  "hillary-clinton=Hillary_Clinton"
  "john-bolton=John_Bolton"
  "john-ratcliffe=John_Ratcliffe_(American_politician)"
  "kamala-harris=Kamala_Harris"
  "isa-bin-salman-al-khalifa=Isa_bin_Salman_Al_Khalifa"
  "bahrain-1994-1996-posting=Bahrain"
  "marty-gottesfeld=Martin_Gottesfeld"
  "arkady-shevchenko=Arkady_Shevchenko"
  "mary-margaret-graham=Mary_Margaret_Graham"
  "bob-grenier=Robert_L._Grenier"
  "jesselyn-radack=Jesselyn_Radack"
  "zero-dark-thirty=Zero_Dark_Thirty"
  "gore-vidal=Gore_Vidal"
  "ray-davis-lahore-shooting=Raymond_Davis_(CIA_contractor)"
  "greater-and-lesser-tunb-islands=Greater_and_Lesser_Tunbs"
  "ron-wyden=Ron_Wyden"
  "reza-pahlavi=Reza_Pahlavi,_Crown_Prince_of_Iran"
  "allen-dulles=Allen_Dulles"
  "kim-philby=Kim_Philby"
  "operation-paperclip=Operation_Paperclip"
  "adnan-khashoggi=Adnan_Khashoggi"
  "john-paul-ii-cia=Pope_John_Paul_II"
  "operation-gladio=Operation_Gladio"
  "bill-clinton=Bill_Clinton"
  "bill-binney=William_Binney_(intelligence_official)"
  "craig-murray=Craig_Murray"
  "manuel-noriega=Manuel_Noriega"
  "bezalel-smotrich=Bezalel_Smotrich"
  "national-archives-declassification=National_Archives_and_Records_Administration"
  "james-clapper=James_Clapper"
  "marco-rubio=Marco_Rubio"
  "colin-powell=Colin_Powell"
  "lawrence-wilkerson=Lawrence_Wilkerson"
  "richard-perle=Richard_Perle"
  "itamar-ben-gvir=Itamar_Ben-Gvir"
  "arnon-milchan=Arnon_Milchan"
  "hamas=Hamas"
  "secret-service=United_States_Secret_Service"
  "will-hurd=Will_Hurd"
  "alec-baldwin=Alec_Baldwin"
  "jennings-randolph=Jennings_Randolph"
  "condoleezza-rice=Condoleezza_Rice"
  "donald-rumsfeld=Donald_Rumsfeld"
  "bashar-al-assad=Bashar_al-Assad"
  "les-wexner=Les_Wexner"
  "sheldon-adelson=Sheldon_Adelson"
  "caspar-weinberger=Caspar_Weinberger"
  "barack-obama=Barack_Obama"
  "shireen-abu-akleh=Shireen_Abu_Akleh"
  "jerry-falwell-jr=Jerry_Falwell_Jr."
  "brett-mcgurk=Brett_McGurk"
  "phil-ochs=Phil_Ochs"
  "robert-f-kennedy-jr=Robert_F._Kennedy_Jr."
  "st-nectarios-of-aegina=Nectarios_of_Aegina"
  "shin-bet=Shin_Bet"
  "st-porphyrios-church-gaza=Church_of_Saint_Porphyrius"
  "taybeh=Taybeh"
  "kent-state=Kent_State_shooting"
  "project-gateway=Stargate_Project"
  "family-jewels=Family_Jewels_(Central_Intelligence_Agency)"
  "greek-intelligence-service=National_Intelligence_Service_(Greece)"
  "sacha-baron-cohen=Sacha_Baron_Cohen"
  "eli-cohen=Eli_Cohen"
  "ghislaine-maxwell=Ghislaine_Maxwell"
  "robert-maxwell=Robert_Maxwell"
  "doing-time-like-a-spy=John_Kiriakou"
  "peter-mandelson=Peter_Mandelson"
  "below-worlds-end=John_Kiriakou"
  "abu-zubaydah=Abu_Zubaydah"
  "benazir-bhutto=Benazir_Bhutto"
  "bill-casey=William_J._Casey"
  "cia=Central_Intelligence_Agency"
  "cia-national-resources-division=Central_Intelligence_Agency"
  "cia-political-psychology-division=Central_Intelligence_Agency"
  "cold-cell=Solitary_confinement"
  "dgse=Directorate-General_for_External_Security"
  "enhanced-interrogation=Enhanced_interrogation_techniques"
  "five-eyes=Five_Eyes"
  "gerald-post=Jerrold_M._Post"
  "guantanamo-bay=Guantanamo_Bay_detention_camp"
  "gust-avrakotos=Gust_Avrakotos"
  "hummus=Hummus"
  "jeff-fahey=Jeff_Fahey"
  "john-brennan=John_O._Brennan"
  "john-kiriakou=John_Kiriakou"
  "jose-rodriguez=Jose_Rodriguez_(intelligence_officer)"
  "lincolns-last-turd=Ford%27s_Theatre"
  "mitchell-and-jessen=Bruce_Jessen"
  "mount-weather=Mount_Weather_Emergency_Operations_Center"
  "operating-directive=Diplomatic_cable"
  "pick-the-man-principle=Robert_H._Jackson"
  "ramzi-bin-al-shibh=Ramzi_bin_al-Shibh"
  "revolutionary-organization-17-november=Revolutionary_Organization_17_November"
  "richard-welch=Richard_Welch"
  "senate-torture-report=Senate_Intelligence_Committee_report_on_CIA_torture"
  "sleep-deprivation=Sleep_deprivation"
  "soylent-green-cable-easter-egg=Soylent_Green"
  "strawberry-fields=Guantanamo_Bay"
  "surveillance-detection-route=Surveillance"
  "the-farm=Camp_Peary"
  "ticking-time-bomb=Ticking_time_bomb_scenario"
  "walling=Wall"
  "welch-45=M1911_pistol"

  # ===== Wiki-trust batch — 2026-05 =====
  # People (obvious 1:1)
  "rudy-giuliani=Rudy_Giuliani"
  "saddam-hussein=Saddam_Hussein"
  "jonathan-pollard=Jonathan_Pollard"
  "sebastian-gorka=Sebastian_Gorka"
  "joe-biden=Joe_Biden"
  "john-kerry=John_Kerry"
  "john-mccain=John_McCain"
  "karl-rove=Karl_Rove"
  "peter-thiel=Peter_Thiel"
  "alex-karp=Alex_Karp"
  "anwar-al-awlaki=Anwar_al-Awlaki"
  "hassan-nasrallah=Hassan_Nasrallah"
  "imran-khan=Imran_Khan"
  "joko-widodo=Joko_Widodo"
  "khaled-mashal=Khaled_Mashal"
  "trita-parsi=Trita_Parsi"
  "michael-hastings=Michael_Hastings_(journalist)"
  "jason-leopold=Jason_Leopold"
  "ted-rall=Ted_Rall"
  "roger-waters=Roger_Waters"
  "jamaal-bowman=Jamaal_Bowman"
  "cori-bush=Cori_Bush"
  "josh-shapiro=Josh_Shapiro"
  "bill-richardson=Bill_Richardson"
  "joshua-schulte=Joshua_Schulte"
  "mike-spann=Johnny_Micheal_Spann"
  "john-walker-lindh=John_Walker_Lindh"
  "prince-muhammad-bin-naif=Mohammed_bin_Nayef"
  "mahmoud-al-mabhouh=Mahmoud_al-Mabhouh"
  "khalid-sheikh-mohammed=Khalid_Sheikh_Mohammed"
  "mohammed-atef=Mohammed_Atef"
  "ali-soufan=Ali_Soufan"
  "john-oneill=John_P._O'Neill"
  "robert-mueller=Robert_Mueller"
  "robert-hanssen=Robert_Hanssen"
  "brian-kelly=Brian_J._Kelley"
  "george-tenet=George_Tenet"
  "william-webster=William_H._Webster"
  "cofer-black=Cofer_Black"
  "gina-haspel=Gina_Haspel"
  "dick-clarke=Richard_A._Clarke"
  "sandy-berger=Sandy_Berger"
  "bob-baer=Robert_Baer"
  "steve-kappes=Stephen_Kappes"
  "james-angleton=James_Jesus_Angleton"
  "admiral-crowe=William_J._Crowe"
  "norman-schwarzkopf=Norman_Schwarzkopf_Jr."
  "wesley-clark=Wesley_Clark"
  "general-dostum=Abdul_Rashid_Dostum"
  "uday-hussein=Uday_Hussein"
  "hussein-kamel=Hussein_Kamel_al-Majid"
  "ali-hassan-al-majid=Ali_Hassan_al-Majid"
  "ahmed-khatib=Ahmed_al-Khatib"
  "ahmed-chalabi=Ahmed_Chalabi"
  "george-habash=George_Habash"
  "april-glaspie=April_Glaspie"
  "sheikh-jaber-al-ahmad=Jaber_Al-Ahmad_Al-Sabah"
  "sheikh-saad-al-abdullah=Saad_Al-Abdullah_Al-Salim_Al-Sabah"
  "saud-nasir-al-sabah=Saud_Nasir_Al-Sabah"
  "skip-gnehm=Edward_W._Gnehm"
  "louis-farrakhan=Louis_Farrakhan"
  "pete-seeger=Pete_Seeger"
  "jeffrey-epstein=Jeffrey_Epstein"
  "bernie-kerik=Bernard_Kerik"
  "bruce-fine=Bruce_Fein"
  "robert-maclean=Robert_MacLean_(whistleblower)"
  "erik-prince=Erik_Prince"
  "john-rendon=John_Rendon"
  "mack-mclarty=Mack_McLarty"
  "john-mccone=John_A._McCone"

  # Events
  "jfk-assassination=Assassination_of_John_F._Kennedy"
  "1993-bush-assassination-plot=Attempted_assassination_of_George_H._W._Bush_in_Kuwait_in_1993"
  "abu-zubaydah-capture=Abu_Zubaydah"
  "qala-i-jangi-uprising=Battle_of_Qala-i-Jangi"
  "kuwait-liberation-day=Liberation_of_Kuwait"
  "kuwait-oil-fires=Kuwaiti_oil_fires"
  "dasht-i-leili-massacre=Dasht-i-Leili_massacre"
  "iran-12-day-war=Iran–Israel_war"
  "bojinka-plot=Bojinka_plot"
  "kiki-camarena-case=Enrique_Camarena"
  "three-saudi-princes=Abu_Zubaydah"
  "yellowcake-niger-forgery=Niger_uranium_forgeries"
  "yemen=Yemen"

  # Organizations
  "aipac=American_Israel_Public_Affairs_Committee"
  "mossad=Mossad"
  "blackwater=Academi"
  "palantir=Palantir_Technologies"
  "in-q-tel=In-Q-Tel"
  "vault-7=Vault_7"
  "mk-ultra=MKUltra"
  "operation-mockingbird=Operation_Mockingbird"
  "pflp=Popular_Front_for_the_Liberation_of_Palestine"
  "special-activities-division=Special_Activities_Center"
  "ground-branch=Special_Activities_Center"
  "grs-global-response-staff=Global_Response_Staff"
  "petra-bank=Petra_Bank"
  "black-cube=Black_Cube"
  "fci-loretto=FCI_Loretto"
  "bluffdale-nsa-facility=Utah_Data_Center"
  "drone-base-balochistan=Shamsi_Airfield"
  "falls-church-mosque=Dar_Al-Hijrah_Islamic_Center"
  "analysis-corporation=The_Analysis_Corporation"

  # Concepts / Procedures
  "hawala-system=Hawala"
  "cia-cable-priority-levels=Diplomatic_cable"
  "executive-order-12333=Executive_Order_12333"
  "title-10-vs-title-50=United_States_Code"
  "tuesday-morning-kill-list=Disposition_Matrix"
  "ninth-circuit-contractor-ruling-2025=United_States_Court_of_Appeals_for_the_Ninth_Circuit"
  "national-endowment-for-democracy=National_Endowment_for_Democracy"

  # ===== Wiki-trust batch — 2026-05 (round 2: post-Cleared Hot + post-Covert Ops + retries) =====
  # Cleared Hot ingest
  "mohamedou-ould-slahi=Mohamedou_Ould_Slahi"
  "khaled-el-masri=Khalid_El-Masri"
  "carlos-the-jackal=Carlos_the_Jackal"
  "mike-hayden=Michael_Hayden_(general)"
  "tom-drake=Thomas_Andrews_Drake"
  "section-702=Section_702_of_the_Foreign_Intelligence_Surveillance_Act"
  "sarah-jane-moore=Sara_Jane_Moore"
  "francis-gary-powers=Francis_Gary_Powers"
  "leon-panetta=Leon_Panetta"

  # Covert Operations Insight ingest
  "ai-weiwei=Ai_Weiwei"
  "andres-serrano=Andres_Serrano"
  "afghan-heroin-policy=Opium_production_in_Afghanistan"
  "harold-james-nicholson=Harold_James_Nicholson"
  "eric-oneill=Eric_O'Neill_(spy)"
  "scholar-in-residence-program=Central_Intelligence_Agency"

  # Retries with alternate titles for previously-failed
  "grs-global-response-staff=United_States_diplomatic_security"
  "fci-loretto=Federal_Correctional_Institution,_Loretto"
  "sandy-berger=Samuel_R._Berger"
  "bob-baer=Robert_Baer_(CIA)"
  "ahmed-khatib=Ahmed_al-Khatib_(Kuwaiti_doctor)"
  "kuwait-liberation-day=Liberation_Day_(Kuwait)"
  "iran-12-day-war=2025_Iran–Israel_war"
  "1993-bush-assassination-plot=April_1993_George_H._W._Bush_assassination_attempt"
  "bill-buckley=William_Francis_Buckley_(CIA_officer)"
  "gerald-post=Jerrold_Post"
  "church-committee=Church_Committee"
  "pike-committee=Pike_Committee"
  "thomas-massie=Thomas_Massie"
  "joe-wilson=Joseph_C._Wilson"
  "edward-snowden=Edward_Snowden"
  "david-petraeus=David_Petraeus"
  "richard-helms=Richard_Helms"
  "patriot-act=Patriot_Act"
  "tora-bora=Tora_Bora"
  "abdul-rashid-dostum=Abdul_Rashid_Dostum"
  "hezbollah=Hezbollah"
  "iran-contra=Iran%E2%80%93Contra_affair"
  "william-donovan=William_J._Donovan"
  "vernon-walters=Vernon_A._Walters"
  "william-friedman=William_F._Friedman"
  "aldrich-ames=Aldrich_Ames"
  "dick-cheney=Dick_Cheney"
  "jane-harman=Jane_Harman"
  "peter-strzok=Peter_Strzok"
  "sandy-grimes=Sandra_Grimes"
  "valerie-plame=Valerie_Plame"
  "jeffrey-sterling=Jeffrey_Sterling_(intelligence_officer)"
  "aq-khan=Abdul_Qadeer_Khan"
  "pervez-musharraf=Pervez_Musharraf"
  "isi=Inter-Services_Intelligence"
  "brian-ross=Brian_Ross_(journalist)"
  "mi6=Secret_Intelligence_Service"
  "extraordinary-rendition=Extraordinary_rendition"

  # ===== Illustrative mappings — 2026-06 (concept/event articles) =====
  "rfk-assassination=Robert_F._Kennedy"
  "maduro-capture=Nicolás_Maduro"
  "bin-laden-tora-bora-escape=Osama_bin_Laden"
  "operation-midnight-climax=MKUltra"
  "waterboarding=Abu_Ghraib_torture_and_prisoner_abuse"
  "ruby-ridge=Randy_Weaver"
  "waco-siege=David_Koresh"
  "learned-helplessness=Martin_Seligman"
  "one-time-pad=Cryptography"
  "sleeper-agent=Rudolf_Abel"
  "thin-thread-stellar-wind=William_Binney_(intelligence_official)"
  "lie-detection=Polygraph"
  "kompromat=KGB"
  "espionage-act=Eugene_V._Debs"
  "israeli-nuclear-program=Negev_Nuclear_Research_Center"
  "havana-syndrome=Embassy_of_the_United_States,_Havana"
  "arlington-cemetery-spies=Arlington_National_Cemetery"
  "cia-drug-facilitation=Contras"
  "diesel-therapy=United_States_Marshals_Service"
  "national-intelligence-council=Director_of_National_Intelligence"
  "senior-executive-service=Executive_Office_of_the_President_of_the_United_States"
  "dashti-leyli=Northern_Alliance"
  "camp-david-final-talks=Israeli–Palestinian_conflict"
  "gay-diplomat-operation=KGB"
  "government-metadata-purchase=PRISM"
  "the-intercept=The_Intercept"
  "national-bird=National_Bird_(film)"
  "signature-strikes=Drone_strikes_in_Pakistan"
  "solitary-confinement=Solitary_confinement"
  # Wave 2 pictures lane (2026-07-05)
  "benjamin-netanyahu=Benjamin_Netanyahu"
  "donald-trump=Donald_Trump"
  "chelsea-manning=Chelsea_Manning"
  "daniel-ellsberg=Daniel_Ellsberg"
  "daniel-hale=Daniel_Hale_(whistleblower)"
  "cory-booker=Cory_Booker"
  "ilhan-omar=Ilhan_Omar"
  "tulsi-gabbard=Tulsi_Gabbard"
  "julian-assange=Julian_Assange"
  "james-jesus-angleton=James_Jesus_Angleton"
  "katherine-gun=Katharine_Gun"
  "meredith-whittaker=Meredith_Whittaker"
  "thomas-drake=Thomas_Andrews_Drake"
  "zbigniew-brzezinski=Zbigniew_Brzezinski"
  "andrew-feinstein=Andrew_Feinstein"
  "bill-barr=William_Barr"
  "pam-bondi=Pam_Bondi"
  "russell-targ=Russell_Targ"
  "daniel-domscheit-berg=Daniel_Domscheit-Berg"
  "eric-swallwell=Eric_Swalwell"
  "pete-hoekstra=Pete_Hoekstra"
  "lee-zeldon=Lee_Zeldin"
  "joe-kent=Joe_Kent_(politician)"
  "fbi=Federal_Bureau_of_Investigation"
  "nsa=National_Security_Agency"
  "national-security-agency=National_Security_Agency"
  "government-accountability-project=Government_Accountability_Project"
  "belmarsh-prison=HM_Prison_Belmarsh"
  "bay-path-university=Bay_Path_University"
  "fort-gordon=Fort_Eisenhower"
  "guantanamo-origin=Guantanamo_Bay_detention_camp"
  "richard-wolff=Richard_D._Wolff"
  "youngstown-sheet-and-tube=Youngstown_Sheet_and_Tube"
  "trump-tariffs=Tariffs_in_the_second_Trump_administration"
  "germany-and-israel=Germany–Israel_relations"
  "antisemitism-and-anti-zionism=Anti-Zionism"
  "gaza-famine=Gaza_famine"
  "9-11-commission=9/11_Commission"
  # ===== Ledger clear-out — 2026-08-04 (all remaining imageless articles) =====
  "1953-iran-coup=1953_Iranian_coup_d'état"
  "aafia-siddiqui=Aafia_Siddiqui"
  "abraham-accords=Abraham_Accords"
  "abu-omar-rendition=Abu_Omar_case"
  "alex-padilla=Alex_Padilla"
  "ali-mohamed=Ali_Mohamed_(double_agent)"
  "american-psychological-association=American_Psychological_Association"
  "amnesty-international=Amnesty_International"
  "arianna-huffington=Arianna_Huffington"
  "aryan-brotherhood=Aryan_Brotherhood"
  "bahrain-prime-minister-mr-10-percent=Khalifa_bin_Salman_Al_Khalifa"
  "bds-movement=Boycott,_Divestment_and_Sanctions"
  "beirut=Beirut"
  "bill-buckley=William_Francis_Buckley"
  "bruce-fein=Bruce_Fein"
  "bureau-of-prisons=Federal_Bureau_of_Prisons"
  "china-djibouti-base=Djibouti"
  "citizens-united=Citizens_United_v._FEC"
  "code-pink=Code_Pink"
  "cold-war=Cold_War"
  "counterterrorism-center=Counterterrorism_Center"
  "covertaction-magazine=CovertAction_Quarterly"
  "curveball=Curveball_(informant)"
  "daniel-hale=Daniel_Hale"
  "dead-drop=Dead_drop"
  "der-spiegel=Der_Spiegel"
  "elon-musk=Elon_Musk"
  "eric-oneill=Eric_O'Neill"
  "felix-rodriguez=Félix_Rodríguez_(soldier)"
  "fisa-court=United_States_Foreign_Intelligence_Surveillance_Court"
  "fisa=Foreign_Intelligence_Surveillance_Act"
  "fort-chapman=Camp_Chapman_attack"
  "freedom-of-information-act=Freedom_of_Information_Act_(United_States)"
  "geneva-conventions=Geneva_Conventions"
  "george-hw-bush=George_H._W._Bush"
  "george-w-bush=George_W._Bush"
  "henry-kissinger=Henry_Kissinger"
  "human-rights-watch=Human_Rights_Watch"
  "india=India"
  "iraq-wmd-intelligence=Iraq_and_weapons_of_mass_destruction"
  "isis=Islamic_State"
  "ismail-haniyeh-assassination=Assassination_of_Ismail_Haniyeh"
  "j-edgar-hoover=J._Edgar_Hoover"
  "jake-tapper=Jake_Tapper"
  "james-bond=James_Bond"
  "james-fishback=James_Fishback"
  "jd-vance=JD_Vance"
  "jeffrey-sterling=Jeffrey_Alexander_Sterling"
  "joe-rogan=Joe_Rogan"
  "joe-weisberg=Joe_Weisberg"
  "juan-guaido=Juan_Guaidó"
  "kandahar=Kandahar"
  "kashmir=Kashmir"
  "khobar-towers-bombing=Khobar_Towers_bombing"
  "kurds=Kurds"
  "kuwait-invasion-intelligence=Iraqi_invasion_of_Kuwait"
  "langley=Langley,_Virginia"
  "lindsey-graham=Lindsey_Graham"
  "maria-butina=Maria_Butina"
  "martin-luther-king=Martin_Luther_King_Jr."
  "matt-dehart=Matt_DeHart"
  "mek=People's_Mojahedin_Organization_of_Iran"
  "mike-pompeo=Mike_Pompeo"
  "monroe-doctrine=Monroe_Doctrine"
  "muammar-gaddafi=Muammar_Gaddafi"
  "national-security-act=National_Security_Act_of_1947"
  "national-security-council=United_States_National_Security_Council"
  "nobel-peace-prize=Nobel_Peace_Prize"
  "nordstream-pipeline-sabotage=Nord_Stream_pipelines_sabotage"
  "olof-palme-assassination=Assassination_of_Olof_Palme"
  "oman=Oman"
  "osama-bin-laden=Osama_bin_Laden"
  "piers-morgan=Piers_Morgan"
  "pricewaterhousecoopers=PricewaterhouseCoopers"
  "project-stargate=Stargate_Project_(U.S._Army_unit)"
  "ptsd=Post-traumatic_stress_disorder"
  "radio-and-tv-marti=Radio_y_Televisión_Martí"
  "ray-mcgovern=Ray_McGovern"
  "robert-maclean=Robert_MacLean"
  "ross-ulbricht=Ross_Ulbricht"
  "roy-cohn=Roy_Cohn"
  "sam-adams-award=Sam_Adams_Award"
  "sara-jane-moore=Sara_Jane_Moore"
  "senate-intelligence-committee=United_States_Senate_Select_Committee_on_Intelligence"
  "somali-land=Somaliland"
  "soviet-union=Soviet_Union"
  "strait-of-hormuz=Strait_of_Hormuz"
  "tucker-carlson=Tucker_Carlson"
  "united-food-and-commercial-workers=United_Food_and_Commercial_Workers"
  "united-fruit-arbenz-coup=1954_Guatemalan_coup_d'état"
  "vietnam-war=Vietnam_War"
  "vladimir-putin=Vladimir_Putin"
  "volodymyr-zelensky=Volodymyr_Zelenskyy"
  "watergate=Watergate_scandal"
  "world-trade-center=World_Trade_Center_(1973–2001)"
  "zawahiri-assassination=Killing_of_Ayman_al-Zawahiri"
  "1993-bush-assassination-plot=George_H._W._Bush"
  "2026-iran-war-economic-shock=Price_of_oil"
  "2026-iran-war=Iran–Israel_war"
  "2028-presidential-field=White_House"
  "9-11-plea-agreements=Guantanamo_Bay_detention_camp"
  "911-attribution-of-responsibility=September_11_attacks"
  "abolish-the-cia=Central_Intelligence_Agency"
  "abraham-lincoln-collection=Abraham_Lincoln"
  "abu-nidal-disruption=Abu_Nidal"
  "administrative-remedy-process=United_States_Department_of_Justice"
  "afghan-languages=Pashto"
  "afghan-war-logs=Afghan_War_documents_leak"
  "afghanistan-2011-kerry-trip=John_Kerry"
  "ai-whistleblower-initiative=Artificial_intelligence"
  "aipac-foreign-agent-registration=American_Israel_Public_Affairs_Committee"
  "akrotiri-village-evacuation=RAF_Akrotiri"
  "al-qaeda-software=Al-Qaeda"
  "al-qaeda-training-manual-interrogation-tactics=Al-Qaeda"
  "albert-stubblebine=Albert_Stubblebine"
  "alex-station=Alec_Station"
  "alexa=Amazon_Alexa"
  "amaryllis-fox-kennedy=Amaryllis_Fox_Kennedy"
  "andy-warhol-encounter=Andy_Warhol"
  "angry-birds=Angry_Birds_(video_game)"
  "antisemitism-and-anti-zionism=Antisemitism"
  "arrais-corporation=Tysons,_Virginia"
  "assange-plea-deal=Julian_Assange"
  "athens-bank-fraud-report=Athens"
  "bahrain-fishing-officer-demarche=Bahrain"
  "bahrain-intifada-1994=1990s_uprising_in_Bahrain"
  "big-assawoman-bay-nasa-launch=Wallops_Flight_Facility"
  "bilderberg-weapon-sales=Bilderberg_meeting"
  "bill-pulte=Bill_Pulte"
  "billy-waugh=Billy_Waugh"
  "bob-trout=Robert_Trout"
  "bob-woodward-cia-access=Bob_Woodward"
  "british-bases-in-cyprus=Akrotiri_and_Dhekelia"
  "bureau-of-prisons-advisory-board=United_States_Department_of_Justice"
  "cameo=Cameo_(website)"
  "central-american-task-force=Contras"
  "chaos-computer-club-wikileaks=Chaos_Computer_Club"
  "charlie-kirk-shooting=Charlie_Kirk"
  "chas-freeman-gaza-plan-1991=Chas_Freeman"
  "china-economic-threat=Economy_of_China"
  "china-illegal-fishing=Fishing_industry_in_China"
  "chinese-spy-balloon-incident=2023_Chinese_balloon_incident"
  "christian-zionism=Christian_Zionism"
  "christopher-hitchens=Christopher_Hitchens"
  "christopher-steele-dossier=Steele_dossier"
  "cia-adultery-culture=Central_Intelligence_Agency"
  "cia-animal-surveillance-experiments=Acoustic_Kitty"
  "cia-arabic-hiring-practices=Arabic"
  "cia-big-tech-revolving-door=Silicon_Valley"
  "cia-car-hacking=Vault_7"
  "cia-cash-room=United_States_one_hundred-dollar_bill"
  "cia-culture-of-lying=Deception"
  "cia-democrats-2016=United_States_House_of_Representatives"
  "cia-disguise-program=Disguise"
  "cia-fbi-911-interagency-rivalry=J._Edgar_Hoover"
  "cia-fbi-budget-fearmongering=J._Edgar_Hoover"
  "cia-fbi-organized-crime=American_Mafia"
  "cia-fbi-social-media-embed=Twitter_Files"
  "cia-feeder-schools=Georgetown_University"
  "cia-founding-1947=National_Security_Act_of_1947"
  "cia-gmail-account-felony-case=Gmail"
  "cia-insiders-guide-to-surveillance=Surveillance"
  "cia-intelligence-failures=Central_Intelligence_Agency"
  "cia-liaison-relationships=Intelligence_agency"
  "cia-media-relations=Operation_Mockingbird"
  "cia-media-revolving-door=Television_news"
  "cia-political-action-group=Propaganda"
  "cia-political-neutrality-tradition=George_H._W._Bush"
  "cia-record-deniability=Plausible_deniability"
  "cia-remote-vehicle-control=Vault_7"
  "cia-satan-church-nsa-investigation=Satanic_panic"
  "cia-sexpionage=Honey_trapping"
  "cia-smart-tv-surveillance=Smart_TV"
  "cia-spy-tech-amazon=Amazon_(company)"
  "cia-torture-program-whistleblowing=Enhanced_interrogation_techniques"
  "cia-training-doctrine=Camp_Peary"
  "cia-ufo-question=Unidentified_flying_object"
  "classification-compartments=Classified_information_in_the_United_States"
  "collateral-murder-video=Collateral_Murder"
  "commercial-off-the-shelf-tradecraft=Commercial_off-the-shelf"
  "communications-management-unit=Communications_management_unit"
  "congressional-intelligence-oversight=United_States_Senate_Select_Committee_on_Intelligence"
  "consortium-news=Robert_Parry_(journalist)"
  "cover-position=Diplomatic_mission"
  "critical-analytic-thinking=Critical_thinking"
  "dark-alliance=Gary_Webb"
  "darpa-lifelog=DARPA"
  "david-rockefeller-bahrain=David_Rockefeller"
  "dead-drop-podcast=Podcast"
  "death-threats-against-kiriakou=John_Kiriakou"
  "decapitation-strikes=Decapitation_strike"
  "deep-state=Deep_state_in_the_United_States"
  "deloitte-consulting-career=Deloitte"
  "democratic-party-2025-approval-decline=Democratic_Party_(United_States)"
  "democratic-redistricting-collapse=Gerrymandering"
  "diary-of-a-ceo-january-2026=Steven_Bartlett"
  "doctor-zhivago-operation=Doctor_Zhivago_(novel)"
  "domino-theory=Ronald_Reagan"
  "double-agent-capture=Double_agent"
  "double-agent-marriott-trap=Marriott_International"
  "eastern-district-of-virginia=United_States_District_Court_for_the_Eastern_District_of_Virginia"
  "economic-roots-of-terrorism=Poverty"
  "epstein-files-transparency-act=Jeffrey_Epstein"
  "ethan-mccord-collateral-murder=Collateral_Murder"
  "f-35-israel-avionics=Lockheed_Martin_F-35_Lightning_II"
  "fbi-apologies-to-kiriakou=Federal_Bureau_of_Investigation"
  "fbi-arrest-strategies=Federal_Bureau_of_Investigation"
  "fbi-manufactured-terrorism-cases=Federal_Bureau_of_Investigation"
  "federal-plea-coercion=Plea_bargain"
  "federal-torture-act=Torture"
  "fentanyl-and-china=Fentanyl"
  "field-loadout=Passport"
  "flock-cameras=Automatic_number-plate_recognition"
  "french-village-lsd-bread-experiment=Pont-Saint-Esprit_mass_poisoning"
  "gail-slater=United_States_Department_of_Justice"
  "galls-com-sponsor-story=Islamabad"
  "gary-webb-kill-the-messenger=Kill_the_Messenger_(2014_film)"
  "george-mcgovern=George_McGovern"
  "girls-madrasa-raid-error=Madrasa"
  "giuliani-pardon-solicitation=Trump_International_Hotel_Washington,_D.C."
  "glenn-symington-act=John_Glenn"
  "graham-netanyahu-icc-tapes=Lindsey_Graham"
  "greek-death-rituals=Ossuary"
  "gulf-security-bargain=Franklin_D._Roosevelt"
  "hague-invasion-act=International_Criminal_Court"
  "hamilton-68=Disinformation"
  "haqqani-white-house-meeting=Ronald_Reagan"
  "haroon-yenor-trial=Terrorism"
  "how-can-i-keep-from-singing=Pete_Seeger"
  "hunter-biden-laptop=Hunter_Biden"
  "intelligence-agencies=United_States_Intelligence_Community"
  "intelligence-identities-protection-act=Central_Intelligence_Agency"
  "iran-2024-drone-retaliation=2024_Iranian_strikes_against_Israel"
  "iran-nuclear-assessment=Nuclear_program_of_Iran"
  "iran-regional-war-2026=Iran"
  "iran-strike-factions-2026=White_House"
  "iranian-sleeper-cells=Islamic_Revolutionary_Guard_Corps"
  "iraq-war-israeli-tower-sabotage=Iraq_War"
  "irish-intelligence-services=Garda_Síochána"
  "israel-boyd-wonder-bread-story=Cemetery"
  "israel-counterintelligence-threat-ranking=Israel–United_States_relations"
  "israel-iran-cell-phone-assassinations=Tehran"
  "israel-turkey-nato-article-5=NATO"
  "israel-united-states-relations=Israel–United_States_relations"
  "israeli-art-student-spy-ring=Mossad"
  "israeli-drone-factories-in-serbia=Serbia"
  "israeli-false-flags=False_flag"
  "israeli-foreknowledge-of-9-11=September_11_attacks"
  "israeli-integration-into-us-agencies=Israel–United_States_relations"
  "israeli-intelligence-in-united-states=Mossad"
  "israeli-property-acquisition-in-greece-and-cyprus=Greece"
  "israeli-torture-of-palestinian-prisoners=Israel_Prison_Service"
  "israeli-training-of-us-police=Israel_Police"
  "italian-election-covert-action=1948_Italian_general_election"
  "jack-murphy-nato-sabotage-story=NATO"
  "japanese-diplomat-fbi-sting=Federal_Bureau_of_Investigation"
  "jim-moran=James_P._Moran"
  "joby-warrick-washington-post-resignation=The_Washington_Post"
  "joe-kent=Joe_Kent_(American_politician)"
  "johns-briefing-room=John_Kiriakou"
  "jordanian-al-qaeda-detainee=Al-Qaeda"
  "joseph-b-chambers=Medal_of_Honor"
  "kathryn-ruemmler=Kathryn_Ruemmler"
  "kiki-camarena-case=Kiki_Camarena"
  "king-abdullah-ii=Abdullah_II_of_Jordan"
  "kiriakou-and-cenk-uygur=Cenk_Uygur"
  "kiriakou-and-third-parties=Third-party_and_independent_candidates_for_the_2016_United_States_presidential_election"
  "kiriakou-cameo-practice=Cameo_(website)"
  "kiriakou-cuba-trip=Havana"
  "kiriakou-cypriot-ancestry=Cyprus"
  "kiriakou-daily-news-diet=Newspaper"
  "kiriakou-death-threats=John_Kiriakou"
  "kiriakou-family-name=Rhodes"
  "kiriakou-father-and-grandfather=Family"
  "kiriakou-greek-whistleblower-law=Hellenic_Parliament"
  "kiriakou-introduction-to-wikileaks=WikiLeaks"
  "kiriakou-iran-trips=Iran"
  "kiriakou-islamabad-surveillance-incident=Islamabad"
  "kiriakou-moneylaundering-tip=Money_laundering"
  "kiriakou-mother-israel-trip=West_Bank"
  "kiriakou-on-travel=Greece"
  "kiriakou-pardon-request=Donald_Trump"
  "kiriakou-podcast-breakthrough=Podcast"
  "kiriakou-prison-designation=Federal_Correctional_Institution,_Loretto"
  "kiriakou-prison-manipulation-tactics=Prison"
  "kiriakou-public-speaking-training=Rhetoric"
  "kiriakou-russian-media=Sputnik_(news_agency)"
  "kiriakou-serial-killer-letters=Serial_killer"
  "kiriakou-situational-awareness=Situation_awareness"
  "kiriakou-television-pilots=Television_pilot"
  "kiriakou-tiktok-fan-edits=TikTok"
  "kiriakou-transfer-to-operations=Central_Intelligence_Agency"
  "kiriakou-writing-process=Writing"
  "kite-runner-rescue-mission=The_Kite_Runner"
  "leadership-profiling=Offender_profiling"
  "lebanon-israeli-conflict=Lebanon"
  "letter-from-loretto=Letter_from_Birmingham_Jail"
  "liberty-university=Liberty_University"
  "loretto-correctional-officers=Prison_officer"
  "loretto-education-department=Federal_Correctional_Institution,_Loretto"
  "lsd-mind-manipulation=Lysergic_acid_diethylamide"
  "lynn-buchanan=Remote_viewing"
  "magic-box=Mobile_phone_tracking"
  "mar-a-lago-pardon-pitch=Mar-a-Lago"
  "marble-framework=Vault_7"
  "mark-levin-iran-policy=Mark_Levin"
  "mark-zuckerberg-angela-merkel-meeting=Mark_Zuckerberg"
  "mass-incarceration-critique=Prison"
  "mass-surveillance=Mass_surveillance"
  "mccain-feinstein-amendment=John_McCain"
  "meredith-whittaker=Signal_(software)"
  "mexican-9-month-work-visas=Mexico–United_States_border"
  "military-ethics=Military_ethics"
  "mir-aimal-kansi-attack=Mir_Aimal_Kansi"
  "miranda-rights=Miranda_warning"
  "mlk-assassination=Assassination_of_Martin_Luther_King_Jr."
  "mohsen-rafighdoost=Mohsen_Rafighdoost"
  "moral-injury=Moral_injury"
  "mormons-in-intelligence=The_Church_of_Jesus_Christ_of_Latter-day_Saints"
  "myanmar-civil-war-kiriakou-view=Myanmar_civil_war_(2021–present)"
  "national-security-vs-civil-liberties=Civil_liberties"
  "ndaa-2027-israel-fusion=National_Defense_Authorization_Act"
  "ndaa-section-219=United_States_Congress"
  "netanyahu-arrest-poll=Benjamin_Netanyahu"
  "newsguard=NewsGuard"
  "non-personal-communication=Dead_drop"
  "nsa-surveillance=National_Security_Agency"
  "october-7-attack=October_7_attacks"
  "office-of-leadership-analysis=Central_Intelligence_Agency"
  "office-of-special-plans-israeli-leak=Office_of_Special_Plans"
  "office-of-the-director-of-national-intelligence=Director_of_National_Intelligence"
  "only-fans=OnlyFans"
  "operation-mega=Federal_Bureau_of_Investigation"
  "operational-vehicles=Toyota_Land_Cruiser"
  "overcriminalization=Prison"
  "pakistan-islam-economic-critique=Pakistan"
  "pakistan-station-2002=Islamabad"
  "palestinians-in-the-gulf=Kuwait"
  "pan-quake=Iceland"
  "permanent-wartime-economy=Military–industrial_complex"
  "petra-bank=Amman"
  "petrodollar-kissinger=Henry_Kissinger"
  "pickaxe-mountain=Natanz"
  "plus-972=Israel"
  "podcast-bros=Podcast"
  "population-decline-analysis=Population_decline"
  "presidents-and-the-cia=Oval_Office"
  "presidents-daily-brief=President's_Daily_Brief"
  "prince-andrew=Prince_Andrew,_Duke_of_York"
  "principals-committee-meeting=United_States_National_Security_Council"
  "prison-food-economy=Prison_food"
  "prison-legal-news=Prison"
  "prison-pedophile-accounts=Prison"
  "prison-phone-monitoring=Telephone"
  "prison-racial-segregation=Prison"
  "private-intelligence=Private_military_company"
  "private-prison-system=Private_prison"
  "project-gateway=Remote_viewing"
  "prosecutorial-careerism=United_States_Attorney"
  "public-interest-defense=Espionage_Act_of_1917"
  "public-safety-factor=Prison"
  "publications-review-board=Central_Intelligence_Agency"
  "rand-paul-eric-holder=Rand_Paul"
  "ray-davis-lahore-shooting=Raymond_Allen_Davis_incident"
  "rdap-program=Drug_rehabilitation"
  "recruitment-attempts-on-kiriakou=John_Kiriakou"
  "remains-of-day-treasury-clerk-story=United_States_Department_of_the_Treasury"
  "remains-of-the-day-book=Cemetery"
  "restraint-camp=Isolationism"
  "rhodes-jewish-deportation-family-story=Rhodes"
  "rhodes-jewish-deportation=Kahal_Shalom_Synagogue"
  "richard-wolff=Marxian_economics"
  "russell-targ=Remote_viewing"
  "russia-ukraine-war-origins=Russo-Ukrainian_War"
  "russiagate=Russian_interference_in_the_2016_United_States_elections"
  "safe-housekeeper=Safe_house"
  "salt-pit=Salt_Pit"
  "san-bernardino-iphone-case=FBI–Apple_encryption_dispute"
  "sanctions-effectiveness=Economic_sanctions"
  "saudi-iran-diplomatic-rivalry=Iran–Saudi_Arabia_relations"
  "saudi-military-composition=Saudi_Arabian_Army"
  "saudi-princes-and-9-11=Abu_Zubaydah"
  "section-702=Foreign_Intelligence_Surveillance_Act"
  "securedrop=SecureDrop"
  "senate-foreign-relations-committee=United_States_Senate_Committee_on_Foreign_Relations"
  "sharia-law=Islam"
  "signature-strikes=General_Atomics_MQ-1_Predator"
  "sigurdur-thordarson=Sigurdur_Thordarson"
  "sociopathic-tendencies=Antisocial_personality_disorder"
  "sofia-bulgaria-dead-drop=Sofia"
  "souda-bay-crete-vulnerability=Naval_Support_Activity_Souda_Bay"
  "south-caucasus-realignment=South_Caucasus"
  "splc-2025-indictment=Southern_Poverty_Law_Center"
  "spy-films-accuracy=Argo_(2012_film)"
  "strait-of-hormuz-transit-fees=Strait_of_Hormuz"
  "superdelegates=Superdelegate"
  "sweat-lodge=Sweat_lodge"
  "taliban-embassy-raid=Peshawar"
  "taliban-spokesman-setup=Taliban"
  "targeting-analyst=Intelligence_analysis"
  "taybeh=Taybeh_Brewing_Company"
  "terry-aubry=Federal_Bureau_of_Investigation"
  "the-botched-pitch=Tradecraft"
  "the-drone-papers=The_Intercept"
  "the-false-volunteer=Interrogation"
  "the-reluctant-spy=John_Kiriakou"
  "the-sociopath-next-door=Antisocial_personality_disorder"
  "the-spy-shop=London"
  "thin-thread=ThinThread"
  "this-desk-kills-fascism=This_Machine_Kills_Fascists"
  "ticking-time-bomb=Torture"
  "todd-blanch=Todd_Blanche"
  "truck-and-cat-in-the-hat=The_Cat_in_the_Hat"
  "truman-cia-op-ed=Harry_S._Truman"
  "trump-cartel-terrorist-designation=Drug_cartel"
  "trump-dni-replacement=Director_of_National_Intelligence"
  "trump-glorification-and-the-iran-war=Donald_Trump"
  "trump-iran-ceasefire-efforts=Donald_Trump"
  "trump-tariffs=Donald_Trump"
  "trump=Donald_Trump"
  "tucker-carlson-2026-fara-referral=Tucker_Carlson"
  "uk-secrecy-laws=Official_Secrets_Act"
  "us-diplomatic-vacancies=United_States_Department_of_State"
  "us-forces-in-syria-legality=Syria"
  "us-military-venture-capital=Venture_capital"
  "usaid-cia-front-operations=United_States_Agency_for_International_Development"
  "va-benefits-for-idf-service=Israel_Defense_Forces"
  "venezuela-boat-strikes=Caribbean_Sea"
  "venezuela-regime-change-2026=Venezuela"
  "venezuelan-embassy-2019=Embassy_of_Venezuela,_Washington,_D.C."
  "veteran-intelligence-professionals-for-sanity=Veteran_Intelligence_Professionals_for_Sanity"
  "virginia-redistricting-supreme-court-ruling=Supreme_Court_of_the_United_States"
  "walk-in=Defection"
  "watching-naval-movements=United_States_Navy"
  "watermark=Watermark"
  "wealth-concentration=Wealth_inequality_in_the_United_States"
  "whispers-in-the-dirt-book=Green-Wood_Cemetery"
  "whistleblower-protection-act=Whistleblower"
  "whistleblower-psychology=Whistleblower"
  "wikileaks-as-a-system=WikiLeaks"
  "witness-k-case=Australian_Secret_Intelligence_Service"
  "yalta-conference=Yalta_Conference"
  "yemen-arrest=Sanaa"
  "zakynthos-holocaust-rescue=Zakynthos"
  # ===== Ledger clear-out fallbacks — 2026-08-04 (targets whose first
  # choice has no free lead image in the Wikipedia summary API) =====
  "dark-alliance=Cocaine"
  "liberty-university=Lynchburg,_Virginia"
  "gerald-post=Central_Intelligence_Agency"
  "ray-davis-lahore-shooting=Lahore"
  "taybeh=Ramallah"
  "enhanced-interrogation=Abu_Ghraib_torture_and_prisoner_abuse"
  "the-farm=Williamsburg,_Virginia"
  "brian-kelly=Federal_Bureau_of_Investigation"
  "in-q-tel=Central_Intelligence_Agency"
  "operation-mockingbird=Propaganda"
  "drone-base-balochistan=Balochistan"
  "khaled-el-masri=Skopje"
  "eric-oneill=Robert_Hanssen"
  "jeffrey-sterling=Central_Intelligence_Agency"
  "extraordinary-rendition=Guantanamo_Bay_detention_camp"
  "katherine-gun=Government_Communications_Headquarters"
  "joe-kent=Washington_(state)"
  "government-accountability-project=Washington,_D.C."
  "antisemitism-and-anti-zionism=Theodor_Herzl"
  "abu-omar-rendition=Milan"
  "citizens-united=Supreme_Court_of_the_United_States"
  "covertaction-magazine=Magazine"
  "project-stargate=Remote_viewing"
  "ptsd=Combat_stress_reaction"
  "united-food-and-commercial-workers=Strike_action"
  "afghan-war-logs=WikiLeaks"
  "ai-whistleblower-initiative=ChatGPT"
  "alex-station=Osama_bin_Laden"
  "cameo=Smartphone"
  "kiriakou-cameo-practice=Smartphone"
  "christian-zionism=Jerusalem"
  "cia-animal-surveillance-experiments=Cat"
  "cia-culture-of-lying=Polygraph"
  "cia-fbi-organized-crime=Al_Capone"
  "cia-fbi-social-media-embed=Twitter"
  "cia-media-relations=CNN"
  "cia-media-revolving-door=CNN"
  "cia-record-deniability=Central_Intelligence_Agency"
  "cia-satan-church-nsa-investigation=Church_of_Satan"
  "cia-torture-program-whistleblowing=Abu_Ghraib_torture_and_prisoner_abuse"
  "cia-training-doctrine=Williamsburg,_Virginia"
  "classification-compartments=Classified_information"
  "commercial-off-the-shelf-tradecraft=Consumer_electronics"
  "communications-management-unit=Solitary_confinement"
  "consortium-news=Washington,_D.C."
  "critical-analytic-thinking=Logic"
  "decapitation-strikes=General_Atomics_MQ-9_Reaper"
  "deep-state=United_States_Capitol"
  "deloitte-consulting-career=New_York_City"
  "democratic-party-2025-approval-decline=United_States_Congress"
  "diary-of-a-ceo-january-2026=Podcast"
  "double-agent-capture=Sting_operation"
  "federal-plea-coercion=Prison"
  "french-village-lsd-bread-experiment=Lysergic_acid_diethylamide"
  "girls-madrasa-raid-error=Pakistan"
  "iran-2024-drone-retaliation=Israel_Defense_Forces"
  "iran-nuclear-assessment=Natanz"
  "kiriakou-and-third-parties=Ralph_Nader"
  "kiriakou-russian-media=Moscow"
  "kiriakou-situational-awareness=Surveillance"
  "kiriakou-television-pilots=Television"
  "military-ethics=United_States_Department_of_Defense"
  "moral-injury=War"
  "mormons-in-intelligence=Salt_Lake_Temple"
  "national-security-vs-civil-liberties=United_States_Bill_of_Rights"
  "ndaa-2027-israel-fusion=The_Pentagon"
  "newsguard=Fake_news"
  "office-of-special-plans-israeli-leak=The_Pentagon"
  "only-fans=Internet"
  "private-prison-system=Prison"
  "public-interest-defense=Daniel_Ellsberg"
  "rdap-program=Alcoholics_Anonymous"
  "restraint-camp=United_States_Capitol"
  "rhodes-jewish-deportation=Rhodes"
  "sanctions-effectiveness=United_Nations"
  "sociopathic-tendencies=Amygdala"
  "the-sociopath-next-door=Amygdala"
  "splc-2025-indictment=Montgomery,_Alabama"
  "spy-films-accuracy=Ben_Affleck"
  "superdelegates=Democratic_National_Convention"
  "targeting-analyst=Central_Intelligence_Agency"
  "trump-cartel-terrorist-designation=Sinaloa_Cartel"
  "us-military-venture-capital=The_Pentagon"
  "veteran-intelligence-professionals-for-sanity=Ray_McGovern"
  "whistleblower-protection-act=Daniel_Ellsberg"
  "whistleblower-psychology=Daniel_Ellsberg"
  "witness-k-case=Australia"
  "yemen-arrest=Yemen"
  "zakynthos-holocaust-rescue=Ionian_Islands"
  "butler-rally-shooting=Attempted_assassination_of_Donald_Trump_in_Pennsylvania"
  "washington-political-culture=United_States_Capitol"
  "cia-directorates=Central_Intelligence_Agency"
  "advanced-counterterrorism-operations=Counterterrorism"
  "asset-acquisition-cycle=Human_intelligence_(intelligence_gathering)"
  "mad-minute=Counterintelligence"
  "access-agent=Social_network"
  "kiriakou-gastrectomy=Gastrectomy"
  "kiriakou-post-gastrectomy-complications=Peptic_ulcer_disease"
  "kiriakou-type-2-diabetes=Type_2_diabetes"
  "kiriakou-on-diet-and-nutrition=Nutrition"
  "kiriakou-on-greek-and-cypriot-food=Halloumi"
  "three-legal-ways-to-enter-a-country=United_Nations_Security_Council"
  "anthony-fauci=Anthony_Fauci"
  "europe-jet-fuel-crisis-2026=Jet_fuel"
  "europe-and-the-2026-iran-war=NATO"
  "2026-strike-wave=Strike_action"
  "the-convenient-terrorist=The_Convenient_Terrorist"
  "gul-rahman=Gul_Rahman"
  "phil-mudd=Philip_Mudd"
  "no-good-guy=Donald_Trump"
  "wolf-blitzer-at-cia-headquarters=Wolf_Blitzer"
  "the-six-hour-queue-for-seats=State_of_the_Union"
  "venezuelan-heavy-crude-refining=PDVSA"
  "the-ask-forgiveness-maxim=Central_Intelligence_Agency"
  "obama-manning-commutation-decision=Chelsea_Manning"
  "kiriakou-uk-speaking-tour=Edinburgh"
  "ballot-name-confusion-tactic=Ballot"
  "the-quarterback-with-a-personal-chef=New_York_Giants"
  "the-cocaine-in-the-west-wing=West_Wing"
  "frank-heart-attack=Federal_Correctional_Institution,_Loretto"
  "the-el-salvador-hotel-drill=Hotel"
  "john-kiriakou-task-force=Federal_Bureau_of_Investigation"
  "the-professor-in-the-visiting-room=Federal_Correctional_Institution,_Loretto"
  "fifth-fleet=United_States_Fifth_Fleet"
  "the-ayatollah-and-the-photographs=Ayatollah"
  "the-washed-out-road-to-the-airport=Baja_California_Sur"
  "the-istanbul-peace-talks=Istanbul"
  "the-cousin-who-stopped-speaking=Washington_Post"
  "tommy-mchale=Port_Authority_of_New_York_and_New_Jersey"
  "signing-with-caa=Creative_Artists_Agency"
  "the-culling-of-friendships=Loneliness"
  "american-media-consolidation=CNN"
  "the-threat-to-testify=Alexandria,_Virginia"
  "kiriakou-guatemala-orphanage-trip=Guatemala_City"
  "the-thirty-seven-analysts=Tulsi_Gabbard"
  "sixteen-employees-to-twenty-thousand=Office_of_the_Director_of_National_Intelligence"
  "syrian-bodyguard=Abu_Zubaydah"
  "the-mental-health-parity-gap=Mental_health"
  "the-state-department-cover-investigation=United_States_Department_of_State"
  "the-mintpress-prediction=Barack_Obama"
  "training-foreign-intelligence-services=Special_Activities_Center"
  "ecuador-is-open-for-business=Ecuador"
  "chilling-effect-of-whistleblower-prosecutions=Espionage_Act_of_1917"
  "the-bolton-raid=John_Bolton"
  "the-october-8-gaza-cars=Gaza_envelope"
  "forcing-iran-toward-a-bomb=Ali_Khamenei"
  "the-hundred-million-a-day-briefing=George_H._W._Bush"
  "netanyahu-and-the-tel-aviv-police-chief=Tel_Aviv"
  "hr-mcmaster=H._R._McMaster"
  "declassifying-for-a-foreign-government=Classified_information_in_the_United_States"
  "slow-rolling-the-president=Central_Intelligence_Agency"
  "the-israelis-are-free-agents=Mossad"
  "signal-and-the-parking-lot=Deep_Throat_(Watergate)"
  "ruining-the-whistleblower=Whistleblower"
  "torture-as-a-recruiting-tool=Islamic_State"
  "ceuta-migrant-crossings-2026=Ceuta"
  "spanish-enclaves-in-north-africa=Plazas_de_soberanía"
  "morocco-algeria-rivalry=Algeria–Morocco_relations"
  "temporary-protected-status=Temporary_protected_status"
  "max-miller=Max_Miller_(politician)"
  "bernie-moreno=Bernie_Moreno"
  "abdul-el-sayed=Abdul_El-Sayed"
  "mike-rogers=Mike_Rogers_(Michigan_politician)"
  "michigan-2026-democratic-senate-primary=United_States_Senate_election_in_Michigan"
  "reality-winner=Reality_Winner"
  "terry-albury=Terry_Albury"
  "jon-ossoff=Jon_Ossoff"
  "mark-warner=Mark_Warner"
  "ro-khanna=Ro_Khanna"
  "jim-jordan=Jim_Jordan"
  "kiriakou-omega-seamaster=Omega_Seamaster"
  "mecca-agreement=Mecca"
  "somaliland-israel-recognition=Somaliland"
  "cu-chi-tunnels=Củ_Chi_tunnels"
  "kiriakou-vietnam-visit-2026=Ho_Chi_Minh_City"
  "the-saigon-cia-station-photograph=Fall_of_Saigon"
  "strait-of-hormuz-reopening-conditions=Strait_of_Hormuz"
  "defense-intelligence-agency=Defense_Intelligence_Agency"
  "jon-stewart=Jon_Stewart"
  "romania-and-us-military-positioning=Romania"
  "civilian-ships-and-piracy=Piracy"
  "turkey-israel-confrontation=Israel–Turkey_relations"
  "the-mcdonalds-theory=McDonald's"
  "iran-elementary-school-strike=Tomahawk_(missile)"
  "rosario-ames=Rosario_Ames"
  "dmitry-polyakov=Dmitri_Polyakov"
  "warrenton-training-center=Warrenton_Training_Center"
  "angela-merkel=Angela_Merkel"
  "john-durham=John_Durham"
  "carter-page=Carter_Page"
  "nigel-farage=Nigel_Farage"
  "zohran-mamdani=Zohran_Mamdani"
  "clive-stafford-smith=Clive_Stafford_Smith"
  "the-war-department-renaming=United_States_Department_of_War"
  "the-tajik-civil-war=Tajikistani_Civil_War"
  "the-sudan-massacre=Sudanese_civil_war_(2023%E2%80%93present)"
  "france-recognizes-palestine=International_recognition_of_the_State_of_Palestine"
  "saudi-arabia-as-an-open-air-prison=Riyadh"
  "the-kafala-sponsorship-system=Kafala_system"
  "the-move-to-fort-myer=Fort_Myer"
  "the-brett-stephens-column=Bret_Stephens"
  "the-macron-defamation-suit=Brigitte_Macron"
  "the-mayflower-madam-analogy=Mayflower_Hotel"
  "the-north-korea-seal-team-six-operation=SEAL_Team_Six"
  "the-plot-to-divert-maduros-plane=Nicol%C3%A1s_Maduro"
  "the-egyptian-berm=Rafah_border_crossing"
  "the-cia-barber-shop=George_Bush_Center_for_Intelligence"
  "the-gabbard-confirmation-fight=Tulsi_Gabbard"
  "the-eric-adams-ambassadorship=Eric_Adams"
  "the-dublin-compensation=Dublin_Airport"
  "pakistani-troops-for-gaza=Pakistan_Armed_Forces"
  "the-kosovo-objection=NATO_bombing_of_Yugoslavia"
  "the-homelessness-executive-order=Homelessness_in_the_United_States"
  "nicholas-burns=R._Nicholas_Burns"
  "dimitris-koufodinas=Dimitris_Koufodinas"
  "john-larson=John_B._Larson"
  "the-baltimore-plot=Baltimore_Plot"
  "the-catering-truck-transfer=Air_Force_One"
  "the-clinton-pakistan-plane-switch=Air_Force_One"
  "the-air-force-one-bomb-threat=Ellinikon_International_Airport"
  "mohammad-reza-pahlavi=Mohammad_Reza_Pahlavi"
  "savak=SAVAK"
  "kharg-island=Kharg_Island"
  "the-disappearance-of-daniel-hale=Daniel_Hale"
  "the-four-question-torture-exam=Liberty_University"
  "the-oath-to-the-constitution=Central_Intelligence_Agency"
  "ranking-bush-obama-trump-biden=Presidents_of_the_United_States"
  "proposals-to-relocate-the-palestinians=Nakba"
  "the-cyprus-fruit-relabel=Cyprus"
  "the-parthenon-view-condo=Parthenon"
  "the-booby-trapped-christmas-cards=Booby_trap"
  "the-calls-not-to-attack-iran=Donald_Trump"
  "the-tarantula-on-the-mini-fridge=Tarantula"
  "the-russian-soldier-in-manama=Manama"
  "eastern-state-penitentiary=Eastern_State_Penitentiary"
  "the-managers-ranking=Joe_Rogan"
  "the-seventh-espionage-defendant=Espionage_Act_of_1917"
  "cofer-black-pre-9-11-warning=Cofer_Black"
  "mojtaba-khamenei=Mojtaba_Khamenei"
  "prison-tattoos=Prison_tattooing"
  "the-toronto-transit-detention=Toronto_Pearson_International_Airport"
  "syrian-minorities-and-the-israeli-strikes=Syria"
  "whistleblower-support-network=Daniel_Ellsberg"
  "kiriakou-acting-career=Screen_Actors_Guild"
  "the-waters-edge-doctrine=Newt_Gingrich"
  "kiriakou-ufo-sighting=Unidentified_flying_object"
  "whether-anyone-is-still-looking-for-zawahiri=Ayman_al-Zawahiri"
  "andrew-bustamante=Andrew_Bustamante"
  "the-spell-your-name-briefing=Mossad"
  "mark-macgann=Uber_Files"
  "mitigating-damage=United_States_district_court"
  "irs-audits-of-kiriakou=Internal_Revenue_Service"
  "kevin-shipp=George_Bush_Center_for_Intelligence"
  "the-rejected-deposits=Anti-money_laundering"
  "the-desert-sunset-photograph=Ministry_of_Interior_(Saudi_Arabia)"
  "the-denials-after-dallas=Assassination_of_John_F._Kennedy"
  "kiriakou-greek-citizenship=Greek_passport"
  "the-dandelion-salad=Dandelion"
  "warrenton-training-center=Warrenton,_Virginia"
  "the-unredacted-copy-paste=Jeffrey_Epstein"
  "chomo=Federal_Correctional_Institution,_Loretto"
  "phil-donahue=Phil_Donahue"
  "ten-minute-moves=Federal_Bureau_of_Prisons"
  "the-knight-ridder-panel=Julian_Assange"
  "the-pondiki-cartoon=Embassy_of_the_United_States,_Athens"
  "the-jenin-incursion=Jenin"
  "albright-in-pyongyang=Madeleine_Albright"
  "the-uyghur-resettlement-trade=UBS"
  "rick-praau=Counterterrorism_Center"
  "the-dorm-as-a-reward=Ghislaine_Maxwell"
  "zunzuneo=United_States_Agency_for_International_Development"
  "the-co-who-wanted-the-cia=Loretto,_Pennsylvania"
  "the-east-mediterranean-gas-partnership=Eastern_Mediterranean"
  "greek-ambassador-dinner-encounter=Ron_Wyden"
  "national-security-letters=National_security_letter"
  "the-fifteen-dollar-maintenance-fee=Bank_of_America"
  "pakistan-without-maps=Faisalabad"
  "israel-and-the-fear-of-being-held-back=Mediterranean_Sea"
  "salman-bin-hamad=Salman_bin_Hamad_Al_Khalifa"
  "more-money-on-security-in-athens-than-beirut=Athens"
  "the-189-undeclared-officers=Embassy_of_Israel,_Washington,_D.C."
  "the-twenty-thousand-dollar-tweet=Jeanine_Pirro"
  "think-tank-financing=Washington,_D.C."
  "the-oreilly-exclusivity-rule=Bill_O%27Reilly_(political_commentator)"
  "sanaa-sewer-project=Sanaa"
  "daniel-duggan=Extradition"
  "censorship-on-the-left=The_Nation"
  "major-non-nato-ally-proposal-for-ukraine=Major_non-NATO_ally"
  "merry-go-round-prank=Prison_uniform"
  "the-hersh-publishing-collapse=Seymour_Hersh"
  "cia-budget-concealment=William_Proxmire"
  "glyburide-incident=Glyburide"
  "the-porn-on-bin-ladens-computers=Osama_bin_Laden"
  "washington-dc-home-rule=District_of_Columbia_Home_Rule_Act"
  "eric-holder=Eric_Holder"
  "rat-and-pedophile-table=Prison"
  "kiriakou-2026-viral-wave=Selfie"
  "the-hundred-and-fifty-foot-limousine=Mitch_McConnell"
  "greek-health-care-system=Healthcare_in_Greece"
  "misleading-headlines=Newspaper"
  "the-emir-of-bahrains-verdict=Hamad_bin_Isa_Al_Khalifa"
  "shank-planting-incident=Shiv_(weapon)"
  "one-hundred-twenty-three-investigations=Jeff_Sessions"
  "frances-haugen=Frances_Haugen"
  "the-crete-blood-feud=Crete"
  "israels-rightward-shift=Aliyah"
  "the-two-officers-who-changed=Counterterrorism_Center"
  "heather-kiriakou=John_Kiriakou"
  "iraq-the-training-account=Iraq"
  "mike-scheuer=Michael_Scheuer"
  "blackmail-of-closeted-politicians=United_States_Capitol"
  "the-gur-sbu-gun-battle=Kyiv"
  "suing-the-cia=United_States_district_court"
  "rival-factions-in-libya=Libya"
  "expanding-the-definition-of-terrorism=Terrorism"
  "the-chinese-professor-on-linkedin=Ministry_of_State_Security_(China)"
  "cia-operational-psychologists=Central_Intelligence_Agency"
  "general-muhammad-equipment-gift=Islamabad"
  "pisces-prison-gang=MS-13"
  "the-house-of-cards-theory=Ali_Khamenei"
  "the-oz-analogy=Oz_(TV_series)"
  "the-stratfor-cables-on-venezuela=Juan_Guaidó"
  "declared-officer=Ellinikon_International_Airport"
  "site-13=Abu_Zubaydah"
  "the-truth-social-announcement=Mar-a-Lago"
  "kiriakou-legal-counteroffensive=Harvard_Law_School"
  "the-nineteen-hundred-dollar-premium=Affordable_Care_Act"
  "the-resort-with-no-air-conditioning=Baja_California_Sur"
  "the-oath-in-the-auditorium=George_Bush_Center_for_Intelligence"
  "targeting-information-between-allies=Iran%E2%80%93Russia_relations"
  "wldragnet=Mass_surveillance_in_the_United_States"
  "the-counterintelligence-exemption=Counterintelligence"
  "iran-posed-no-threat=International_Atomic_Energy_Agency"
  "the-briefing-held-off-campus=Mossad"
  "speakers-office-gatekeeping=Speaker_of_the_United_States_House_of_Representatives"
  "prison-depression=Federal_prison"
  "how-the-cia-kills=Suppressor"
  "kiriakou-shortwave-listening=Shortwave_radio"
  "saudi-television=Saudi_Broadcasting_Authority"
  "the-hundred-city-tour=Belfast"
  "no-ethics-training-at-the-cia=Directorate_of_Operations_(CIA)"
  "steven-lalas=Greek_National_Intelligence_Service"
  "israeli-interception-of-us-secure-calls=Signals_intelligence"
  "hazara-judo-belts=Hazaras"
  "saudi-arabia-and-radicalism=Wahhabism"
  "russia-is-not-the-gravest-threat=Secret_Intelligence_Service"
  "the-giuliani-epstein-emails=Rudy_Giuliani"
  "no-bad-food-in-athens=Greek_cuisine"
  "corkscrew-landings-in-afghanistan=Bagram_Airfield"
  "snowden-did-not-defect=Sheremetyevo_International_Airport"
  "impeach-him-again=United_States_House_of_Representatives"
  "the-guardian-smear-series=The_Guardian"
  "the-search-for-a-country-to-take-gaza=South_Sudan"
  "blueprint-for-free-speech=WikiLeaks"
  "james-morris=People's_Protection_Units"
  "six-different-passports=United_States_passport"
  "greta-zimmer-friedman=V-J_Day_in_Times_Square"
  "the-french-human-sources=DGSE"
  "marlon-beard=Federal_Correctional_Institution,_Loretto"
  "the-eritrea-prohibition=Eritrea"
  "clyde-hall=James_Traficant"
  "the-nine-months-on-food-stamps=Supplemental_Nutrition_Assistance_Program"
  "the-libya-policy-reversal=Muammar_Gaddafi"
  "the-nine-eleven-truth-honorarium=World_Trade_Center_(1973–2001)"
  "the-jay-jones-texts=Virginia"
  "the-hannity-lockerbie-exchange=Sean_Hannity"
  "the-atf-funding-rider=Bureau_of_Alcohol,_Tobacco,_Firearms_and_Explosives"
  "the-yale-intern-fascist=Yale_University"
  "intelligence-peddlers=Embassy"
  "the-las-vegas-case=Las_Vegas"
  "donnie-reynolds-jr=Communications_Management_Unit"
  "leonard-peltier=Leonard_Peltier"
  "fridays-at-the-agency=Central_Intelligence_Agency"
  "the-royal-family-at-taif=Taif"
  "taliban-spokesman-setup=Federal_Correctional_Institution,_Loretto"
  "leonie-brinkema=Albert_V._Bryan_United_States_Courthouse"
  "mexico-city-as-an-espionage-hub=Mexico_City"
  "the-underlying-sadness=Depression_(mood)"
  "jean-gately=Bay_of_Pigs_Invasion"
  "russia-nato-membership=NATO"
  "yemen-jazz-radio-plan=Sanaa"
  "the-bureau-answers-to-no-one=Federal_Bureau_of_Prisons"
  "the-afghans-in-diplomatic-limbo=Al_Udeid_Air_Base"
  "the-golf-course-deed-forgery=Golf_course"
  "italian-intelligence-services=Agenzia_Informazioni_e_Sicurezza_Esterna"
  "mark-lanzotti=Jersey_Shore"
  "the-lafayette-square-tents=Lafayette_Square,_Washington,_D.C."
  "operational-cable=Directorate_of_Operations_(CIA)"
  "the-perplexity-subscription=ChatGPT"
  "the-bridgeton-and-the-tanker-escorts=SS_Bridgeton"
  "the-tier-one-walk-up=Gust_Avrakotos"
  "cleaning-up-after-tora-bora=Battle_of_Tora_Bora"
  "the-bowl-of-dates=Date_(fruit)"
  "the-greenland-prediction=Greenland"
  "the-indonesian-recruitment-question=Jakarta"
  "taking-the-ball-and-going-home=Butler,_Pennsylvania"
  "the-voice-vote-on-the-epstein-files=Chuck_Schumer"
  "the-thirty-year-old-nominee=Office_of_Special_Counsel"
  "the-jerusalem-bluff=Jerusalem"
  "cia-pentagon-war-divide=The_Pentagon"
  "the-four-requirements-of-a-coup=United_States_Military_Academy"
  "the-addis-ababa-zoo=Addis_Ababa"
  "kiriakou-skeet-shooting=Skeet_shooting"
  "the-paris-rifle-serial-number=M4_carbine"
  "spy-films-on-screen=James_Bond"
  "the-condoleezza-rice-meeting=Condoleezza_Rice"
  "colonel-khaled=Inter-Services_Intelligence"
  "bigger-than-the-russian-embassy=Cairo"
  "the-dnc-in-debt=Democratic_National_Committee"
  "barry-eisler=Barry_Eisler"
  "directorate-of-operations=Central_Intelligence_Agency"
  "the-au-pair-who-became-a-stockholm-police-officer=Stockholm"
  "fentanyl-as-a-weapon-of-mass-destruction=Fentanyl"
  "the-iranians-only-have-to-survive=Tehran"
  "presidential-call-memcons=Situation_Room"
  "the-caspian-drone-strike=Caspian_Sea"
  "the-hundred-eighty-seven-israeli-officers=Mossad"
  "directorate-of-intelligence=CIA_headquarters"
  "suggested-responses=Fox_News"
  "the-pardoned-january-6th-defendants=January_6_United_States_Capitol_attack"
  "the-thrown-sandwich=District_of_Columbia_National_Guard"
  "muddling-through=Cold_War"
  "the-armenian-podcasters=Armenian_diaspora"
  "the-seventy-two-year-old-contractor=Central_Intelligence_Agency"
  "us-incarceration-rate=Incarceration_in_the_United_States"
  "passing-time-at-loretto=Federal_Correctional_Institution,_Loretto"
  "robert-david-steele=Podcast"
  "learning-to-dive-in-the-embassy-pool=Sharm_El_Sheikh"
  "the-sahel-church-burnings=Boko_Haram"
  "bulldozing-the-olive-orchards=Olive"
  "daniel-pearl=Daniel_Pearl"
  "us-overseas-basing-footprint=Military_base"
  "the-interrupted-break-in=Lock_picking"
  "dog-food-memo=Federal_Correctional_Institution,_Loretto"
  "barry-pollock=Saipan"
  "the-empire-on-the-ropes=Uncle_Sam"
  "the-least-i-could-do=Restaurant"
  "hire-a-lawyer-first=Lawyer"
  "prison-service-economy=Prison_commissary"
  "the-empty-church-of-the-holy-sepulchre=Church_of_the_Holy_Sepulchre"
  "chief-of-station=Central_Intelligence_Agency"
  "the-supporters-who-could-not-be-public=Central_Intelligence_Agency"
  "the-kuwaiti-cargo-in-yuan=Renminbi"
  "permanent-multipolar-world=BRICS"
  "palestine-house=Miko_Peled"
  "an-actual-summit=Anchorage,_Alaska"
  "the-san-francisco-bacterium-release=San_Francisco"
  "ed-martin=Federal_pardons_in_the_United_States"
  "tony-mendez=Tony_Mendez"
  "the-french-in-the-streets=Yellow_vests_protests"
  "a-middle-east-reading-list=Sykes%E2%80%93Picot_Agreement"
  "the-coffee-with-the-jordanian-intern=Amman"
  "dewey-clarridge=Iran%E2%80%93Contra_affair"
  "find-a-grave=Cemetery"
  "first-recruitment-in-athens=Athens"
  "qat-in-yemen=Khat"
  "mariel-boatlift-comparison=Mariel_boatlift"
  "the-two-tunisians=Faisalabad"
  "bruno-jordan-operation=Amman"
  "the-intercept-source-exposures=The_Intercept"
  "i-should-have-gone-to-film-school=Filmmaking"
  "the-new-jersey-drones=Unmanned_aerial_vehicle"
  "clock-tower-x=ChatGPT"
  "the-mayflower-madam-analogy=Mayflower_Hotel"
  "cia-crimes-reports=Central_Intelligence_Agency"
  "the-martyrdom-bonus=Al-Qaeda"
  "kill-them-all=Counterterrorism_Center"
  "rule-six-endurance=Federal_prison"
  "the-second-plane=United_Airlines_Flight_175"
  "the-laura-ingraham-exchange=Laura_Ingraham"
  "the-1996-campaign-contribution-disclosure=Bob_Dole"
  "jennifer-matthews=Camp_Chapman_attack"
  "the-weight-of-the-government=United_States_Department_of_Justice"
  "greater-israel=Zionism"
  "the-woman-escorted-from-the-white-house=White_House"
  "the-clinton-era-asset-cull=Directorate_of_Operations_(CIA)"
  "the-twenty-five-in-pakistan=Jeanne_Shaheen"
  "the-airbridge=Larnaca_International_Airport"
  "djibouti=Camp_Lemonnier"
  "a-virtual-state-of-war-with-venezuela=Marco_Rubio"
  "the-nineteen-intelligence-agencies=United_States_Intelligence_Community"
  "virginia-pardon-and-voting-rights=Terry_McAuliffe"
  "the-rebuttal-book=George_Tenet"
  "false-flags-are-too-hard=False_flag"
  "the-piers-morgan-panel=Piers_Morgan"
  "chinas-generals-without-combat-experience=People's_Liberation_Army"
  "sharon-scranage=Ghana"
  "presidential-appetite-for-intelligence=President's_Daily_Brief"
  "where-he-slept-in-afghanistan=Bagram_Airfield"
  "hes-been-ours-since-the-seventies=Cocktail_party"
  "walter-pincus=Gary_Webb"
  "second-chance-act=Federal_Bureau_of_Prisons"
  "the-iowa-republican-exchange=Republican_Party_of_Iowa"
  "prison-as-temporary-duty=Federal_prison"
  "dave-phillips=Federal_Correctional_Institution,_Loretto"
  "imia-crisis=Imia/Kardak"
  "the-mob-vote-for-trump=Donald_Trump"
  "james-risen=James_Risen"
  "the-cnn-india-refusal=CNN"
  "abu-zubaydah-as-a-sounding-board=Abu_Zubaydah"
  "air-wars-are-overrated=Aerial_warfare"
  "six-ways-from-sunday=Chuck_Schumer"
  "the-cia-buyout-offer=Central_Intelligence_Agency"
  "the-hotel-room-cover=Hotel"
  "the-2025-india-pakistan-clash-assessment=Line_of_Control"
  "the-hundred-dollar-informants=Afghan_refugees"
  "the-shu-loophole=Solitary_confinement"
  "matthew-cole=The_Intercept"
  "the-blacked-out-grand-jury-minutes=Jeffrey_Epstein"
  "destroying-the-dome-of-the-rock=Dome_of_the_Rock"
  "the-witness-letter=Rudy_Giuliani"
  "the-rogue-officer-remark=George_W._Bush"
  "the-family-that-spans-the-spectrum=Dodecanese"
  "kiriakou-operational-eating=Mango"
  "gavin-newsom=Gavin_Newsom"
  "the-question-about-the-showers=Federal_prison"
  "carrying-classified-out-of-a-scif=Classified_information"
  "the-greek-offer-for-the-bamiyan-buddhas=Buddhas_of_Bamyan"
  "the-capitol-hill-cocaine-ring=United_States_Congress"
)

# Collect entries in a temp dir, assemble JSON at the end.
TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

got=0
miss=0

# ---------------------------------------------------------------------------
# Duplicate-image guard.
#
# A slug may list several titles; later ones are fallbacks for when the first
# has no lead image. That is useful, but a *generic* fallback shared by many
# slugs quietly gives all of them the same picture — this is how nine unrelated
# tradecraft articles ended up illustrated with the same 1920s couple from the
# "Espionage" page. The reuse was invisible because each slug writes its own
# file name.
#
# So: claim each image by content hash. A first-choice title is allowed to
# collide (the CIA seal genuinely belongs on several CIA articles), but a
# fallback that lands on a picture another article already uses is rejected —
# no image beats the wrong image, and the miss shows up in the run summary.
HASHDIR="$TMP/hashes"
mkdir -p "$HASHDIR"

hash_of() { md5 -q "$1" 2>/dev/null || md5sum "$1" 2>/dev/null | cut -d' ' -f1; }

# Returns 0 if this slug now owns the hash, 1 if another slug already does.
claim_hash() {
  local h="$1" slug="$2"
  if mkdir "$HASHDIR/$h" 2>/dev/null; then
    printf '%s' "$slug" > "$HASHDIR/$h/owner"
    return 0
  fi
  [ "$(cat "$HASHDIR/$h/owner" 2>/dev/null)" = "$slug" ]
}

hash_owner() { cat "$HASHDIR/$1/owner" 2>/dev/null; }

# Seed the claims with every image already on disk, so a new fetch can tell it
# is about to duplicate one of them.
for existing_img in "$DEST"/*; do
  [ -f "$existing_img" ] || continue
  case "$(basename "$existing_img")" in credits.json) continue ;; esac
  seed_slug=$(basename "$existing_img"); seed_slug="${seed_slug%.*}"
  claim_hash "$(hash_of "$existing_img")" "$seed_slug" >/dev/null 2>&1 || true
done

export HASHDIR
export -f hash_of claim_hash hash_owner

# Carry forward credits for slugs that already have both an image on disk and
# a good credits entry. Without this, every run re-queries ~700 unchanged
# entries and the resulting load starves the handful that still need fetching.
# Set REFRESH_CREDITS=1 to re-query everything from scratch.
if [ "${REFRESH_CREDITS:-0}" != "1" ] && [ -s "$CREDITS" ]; then
  carried=$(jq -r 'keys[]' "$CREDITS" 2>/dev/null)
  for slug in $carried; do
    [ -n "$(ls "$DEST/$slug".* 2>/dev/null | head -1)" ] || continue
    jq -c --arg k "$slug" '.[$k]' "$CREDITS" > "$TMP/$slug.json"
  done
  echo "Carried forward $(ls "$TMP" | wc -l | tr -d ' ') existing credits (REFRESH_CREDITS=1 to redo)."
fi

# Ask Wikipedia for a page's lead image. Retries with backoff — under
# parallel load the REST API drops requests, and a single miss would
# otherwise be indistinguishable from "this page has no picture".
wp_thumb() {
  local title="$1" attempt json thumb
  for attempt in 1 2 3 4; do
    json=$(curl -sL --max-time 25 -A "$UA" \
      "https://en.wikipedia.org/api/rest_v1/page/summary/$title" 2>/dev/null)
    thumb=$(echo "$json" | jq -r '.originalimage.source // .thumbnail.source // empty' 2>/dev/null)
    if [ -n "$thumb" ] && [ "$thumb" != "null" ]; then
      echo "$thumb"
      return 0
    fi
    # A real page summary that simply has no image: stop, don't retry.
    # Error bodies (429 rate-limit, 404) also carry a "title" field, so key
    # off .titles.canonical, which only a genuine page summary has.
    if echo "$json" | jq -e '.titles.canonical' >/dev/null 2>&1; then
      return 1
    fi
    sleep $((attempt * 2))
  done
  return 1
}

fetch_credit() {
  local thumb="$1"
  local url_basename="${thumb##*/}"
  local file_for_meta="$url_basename"
  if [[ "$thumb" == *"/thumb/"* ]]; then
    file_for_meta=$(echo "$thumb" | sed -E 's|.*/thumb/[^/]+/[^/]+/([^/]+)/.*|\1|')
  fi

  local meta_json
  meta_json=$(curl -sL -A "$UA" "https://commons.wikimedia.org/w/api.php?action=query&titles=File:${file_for_meta}&prop=imageinfo&iiprop=extmetadata&format=json" 2>/dev/null)
  local artist license
  artist=$(echo "$meta_json" | jq -r '.. | objects | .Artist?.value // empty' 2>/dev/null | head -1 | sed -E 's/<[^>]+>//g' | tr -d '\n' | head -c 200)
  license=$(echo "$meta_json" | jq -r '.. | objects | .LicenseShortName?.value // empty' 2>/dev/null | head -1 | tr -d '\n')
  [ -z "$artist" ] && artist="Unknown"
  [ -z "$license" ] && license="See Wikimedia Commons"
  echo "$artist|||$license"
}

do_entry() {
  local entry="$1"
  local slug="${entry%%=*}"
  local titles="${entry#*=}"
  local existing ext thumb url_basename out artist license title

  # Candidate titles, tried in order — later entries in MAPPING act as
  # fallbacks for a slug whose first title has no lead image.
  local -a candidates
  IFS='|' read -r -a candidates <<< "$titles"
  title="${candidates[0]}"

  # Already carried forward from a previous run — nothing to do.
  [ -s "$TMP/$slug.json" ] && return 0

  # If image already exists, just rebuild the credits entry from Wikipedia/Commons.
  existing=$(ls "$DEST/$slug".* 2>/dev/null | head -1)
  if [ -n "$existing" ]; then
    ext="${existing##*.}"
    # Re-derive the thumb URL so we can fetch up-to-date Commons metadata.
    thumb=""
    for title in "${candidates[@]}"; do
      thumb=$(wp_thumb "$title")
      [ -n "$thumb" ] && break
    done
    if [ -z "$thumb" ]; then
      title="${candidates[0]}"
      echo "→ $slug (image present, credit unavailable)"
      printf '{"file":"/images/%s.%s","source_article":%s,"artist":"Unknown","license":"See Wikimedia Commons","via":"Wikimedia Commons"}' \
        "$slug" "$ext" "$(jq -Rn --arg v "$title" '$v')" > "$TMP/$slug.json"
      return 0
    fi
    IFS='|||' read -r artist _ _ license <<< "$(fetch_credit "$thumb")"
    printf '{"file":"/images/%s.%s","source_article":%s,"artist":%s,"license":%s,"via":"Wikimedia Commons"}' \
      "$slug" "$ext" "$(jq -Rn --arg v "$title" '$v')" "$(jq -Rn --arg v "$artist" '$v')" "$(jq -Rn --arg v "$license" '$v')" > "$TMP/$slug.json"
    echo "→ $slug.$ext (credit refreshed: $license)"
    return 0
  fi

  # No image yet — fetch from Wikipedia, trying each candidate title.
  # Remember whether we had to fall back; the duplicate guard below is strict
  # about fallbacks and lenient about a slug's own first choice.
  local from_fallback=0 cand_idx=0
  thumb=""
  for title in "${candidates[@]}"; do
    thumb=$(wp_thumb "$title")
    if [ -n "$thumb" ]; then
      [ "$cand_idx" -gt 0 ] && from_fallback=1
      break
    fi
    cand_idx=$((cand_idx + 1))
  done
  if [ -z "$thumb" ]; then
    echo "✗ $slug (${candidates[*]}) — no lead image"
    return 1
  fi

  # Extension comes from the file name only — strip any query string or
  # fragment, and fall back to .jpg if what's left isn't a real image suffix.
  url_basename="${thumb##*/}"
  url_basename="${url_basename%%\?*}"
  url_basename="${url_basename%%#*}"
  ext=$(echo "${url_basename##*.}" | tr '[:upper:]' '[:lower:]')
  case "$ext" in
    jpg|jpeg|png|gif|svg|webp|tif|tiff) ;;
    *) ext="jpg" ;;
  esac
  out="$DEST/$slug.$ext"
  # upload.wikimedia.org throttles bulk downloads by serving an HTML error
  # page with a 200. Verify we actually got an image, and retry if not.
  local dl_ok=0 dl_try mime
  for dl_try in 1 2 3 4; do
    curl -sL --max-time 60 --retry 0 -A "$UA" -o "$out" "$thumb"
    if [ -s "$out" ]; then
      mime=$(file -b --mime-type "$out" 2>/dev/null)
      case "$mime" in
        image/*) dl_ok=1; break ;;
      esac
    fi
    # 429 from upload.wikimedia.org — back off hard, it is a shared budget.
    sleep $((dl_try * dl_try * 15))
  done
  if [ "$dl_ok" != "1" ]; then
    echo "✗ $slug — download did not yield an image (last type: ${mime:-empty})"
    rm -f "$out"
    return 1
  fi

  # Duplicate guard — see the note above the hash helpers.
  local img_hash owner
  img_hash=$(hash_of "$out")
  if [ -n "$img_hash" ] && ! claim_hash "$img_hash" "$slug"; then
    owner=$(hash_owner "$img_hash")
    if [ "$from_fallback" = "1" ]; then
      echo "✗ $slug — fallback '$title' duplicates the image already used by '$owner'; left without one"
      rm -f "$out"
      return 1
    fi
    echo "! $slug — shares '$title' image with '$owner' (first-choice title, kept)"
  fi

  IFS='|||' read -r artist _ _ license <<< "$(fetch_credit "$thumb")"
  printf '{"file":"/images/%s.%s","source_article":%s,"artist":%s,"license":%s,"via":"Wikimedia Commons"}' \
    "$slug" "$ext" "$(jq -Rn --arg v "$title" '$v')" "$(jq -Rn --arg v "$artist" '$v')" "$(jq -Rn --arg v "$license" '$v')" > "$TMP/$slug.json"
  echo "✓ $slug.$ext ($license)"
  return 0
}

# Run the mapping in parallel — a serial pass over ~1,000 entries takes hours.
# Set PARALLEL=1 to crawl when upload.wikimedia.org starts throttling downloads.
export -f do_entry fetch_credit wp_thumb
export DEST TMP UA
ENTRIES=$(printf '%s\n' "${MAPPING[@]}" | awk -F= '
  { slug=$1; sub(/^[^=]*=/, "", $0); title=$0
    if (!(slug in seen)) { order[++n]=slug; seen[slug]=title }
    else if (index("|" seen[slug] "|", "|" title "|") == 0) { seen[slug]=seen[slug] "|" title } }
  END { for (i=1;i<=n;i++) print order[i] "=" seen[order[i]] }')

printf '%s\n' "$ENTRIES" | tr '\n' '\0' | \
  xargs -0 -P "${PARALLEL:-4}" -I{} bash -c 'do_entry "$@"' _ {}

got=$(ls "$TMP"/*.json 2>/dev/null | wc -l | tr -d ' ')
miss=$(( $(printf '%s\n' "$ENTRIES" | wc -l | tr -d ' ') - got ))

# Assemble credits.json
echo "{" > "$CREDITS"
first=true
for f in "$TMP"/*.json; do
  [ -e "$f" ] || continue
  slug=$(basename "$f" .json)
  if [ "$first" = false ]; then echo "," >> "$CREDITS"; fi
  first=false
  printf '  "%s": %s' "$slug" "$(cat "$f")" >> "$CREDITS"
done
echo "" >> "$CREDITS"
echo "}" >> "$CREDITS"

echo
echo "Summary: $got entries in credits.json, $miss missing images"
